FROM node:18-alpine3.18 AS base

FROM base AS dependencies

RUN apk add --no-cache libc6-compat

WORKDIR /app
COPY ./package.json ./yarn.lock ./
RUN yarn install --frozen-lockfile

#################################

FROM base AS production

ENV SKIP_ENV_VALIDATION true

WORKDIR /app
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

ARG DATABASE_URL=not-set
ENV DATABASE_URL=$DATABASE_URL

ARG NEXT_PUBLIC_PUBNUB_PUBLISH_KEY=not-set
ENV NEXT_PUBLIC_PUBNUB_PUBLISH_KEY=$NEXT_PUBLIC_PUBNUB_PUBLISH_KEY

ARG NEXT_PUBLIC_PUBNUB_SUBSCRIBE_KEY=not-set
ENV NEXT_PUBLIC_PUBNUB_SUBSCRIBE_KEY=$NEXT_PUBLIC_PUBNUB_SUBSCRIBE_KEY

ARG NEXT_PUBLIC_PUBNUB_USER_ID=not-set
ENV NEXT_PUBLIC_PUBNUB_USER_ID=$NEXT_PUBLIC_PUBNUB_USER_ID

ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=not-set
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY

ARG SERVER_AWS_REGION=not-set
ENV SERVER_AWS_REGION=$SERVER_AWS_REGION

ARG SERVER_AWS_S3_BUCKET_NAME=not-set
ENV SERVER_AWS_S3_BUCKET_NAME=$SERVER_AWS_S3_BUCKET_NAME

ARG NEXT_PUBLIC_ENVIRONMENT=not-set
ENV NEXT_PUBLIC_ENVIRONMENT=$NEXT_PUBLIC_ENVIRONMENT

RUN npx prisma generate
RUN npx prisma migrate deploy

RUN yarn build

ENV NODE_ENV production
ENV PORT 3000

EXPOSE 3000

CMD ["node_modules/.bin/next", "start"]